[package]
name = "frontend-wasm"
version = "0.0.1"
authors = ["Daniel Gallups <dsgallups@protonmail.com>"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]
path = "./src/lib/wasm/src/lib.rs"

[dependencies]
wasm-bindgen = "0.2.95"
